export * from './about'
export * from './contact'
export * from './footer'
export * from './hero'
export * from './nav-bar'
export * from './registration'
export * from './sport-card'
export * from './sports'